CREATE TABLE DATA (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	ADDED DATE NOT NULL,
	OPTION_ID INTEGER NOT NULL,
	NUMBEROFDAYS INTEGER,
	PRIMARY KEY (ID)
);
CREATE TABLE DATA_DETAILS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DATA_ID INTEGER NOT NULL,
	TEMPERATURE DECIMAL(5) NOT NULL,
	TEMPERATUREMIN DECIMAL(5) NOT NULL,
	TEMPERATUREMAX DECIMAL(5) NOT NULL,
	HUMIDITY DECIMAL(5) NOT NULL,
	PRESSURE DECIMAL(5) NOT NULL,
	SPEED DECIMAL(5) NOT NULL,
	DIRECTION DECIMAL(5) NOT NULL,
	RAIN DECIMAL(5) NOT NULL,
	"DATE" VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE WEATHER_OPTIONS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	OPTIONS VARCHAR(255),
	PRIMARY KEY (ID)
);
ALTER TABLE DATA_DETAILS
	ADD FOREIGN KEY (DATA_ID) 
	REFERENCES DATA (ID);

INSERT INTO WEATHER_OPTIONS(ID, OPTIONS) VALUES (1, '5 dniowa z dokładnością 3 godzinną');
INSERT INTO WEATHER_OPTIONS(ID, OPTIONS) VALUES (2, '1-16 dniowa z dokładnością dzienną');
